Region.objects.create(name='nissia', extremity=0.2, base=3, power=5, pretty_name='Nissia')
Region.objects.create(name='thewhip', extremity=0.2, base=5, power=10, pretty_name='The Whip')
Region.objects.create(name='kellarn', extremity=0.2, base=5, power=10, pretty_name='Kellarn')
Region.objects.create(name='centriss', extremity=0.3, base=4, power=10, pretty_name='Centriss')
Region.objects.create(name='essianfoothills', extremity=0.2, base=5, power=10, pretty_name='Essian Foothills')
Region.objects.create(name='shipyards', extremity=0.1, base=5, power=7, pretty_name='The Shipyards')
Region.objects.create(name='firstcity', extremity=0.2, base=3, power=7, pretty_name='The First City')
Region.objects.create(name='xilewood', extremity=0.5, base=10, power=10, pretty_name='The Xilewood')
Region.objects.create(name='emmel', extremity=0.2, base=5, power=10, pretty_name='Emmel')
Region.objects.create(name='tirelessnight', extremity=0.65, base=3, power=10, pretty_name = 'The Tireless Night')
Region.objects.create(name='tentacular', extremity=0.7, base=10, power=10, pretty_name = 'The Tentacular')
Region.objects.create(name='thewanderlands', extremity=0.2, base=5, power=10, pretty_name = 'The Wanderlands')
Region.objects.create(name='ostentia', extremity=0.45, base=5, power=5, pretty_name = 'Ostentia')
Region.objects.create(name='thehub', extremity=0.2, base=5, power=10, pretty_name='The Hub')
Region.objects.create(name='theworldspine', extremity=0.2, base=5, power=10, pretty_name='The Worldspine')
Region.objects.create(name='sinisteria', extremity=0.2, base=5, power=10, pretty_name='Sinisteria')
Region.objects.create(name='riddlewood', extremity=0.2, base=5, power=10,pretty_name='The Riddlewoods')
Region.objects.create(name='lostpeaks', extremity=0.2, base=5, power=10, pretty_name='The Lost Peaks')
Region.objects.create(name='mormiria', extremity=0.2, base=5, power=10, pretty_name='Mormiria')
Region.objects.create(name='reyawinn', extremity=0.2, base=5, power=10, pretty_name='Reyawinn')
for r in Region.objects.all():
	r.save()