Region.objects.update_or_create(name='nissia', defaults={'extremity': 0.2, 'base': 3, 'power': 5, 'pretty_name': 'Nissia'})
Region.objects.update_or_create(name='thewhip', defaults={'extremity': 0.2, 'base': 5, 'power': 10, 'pretty_name': 'The Whip'})
Region.objects.update_or_create(name='kellarn', defaults={'extremity': 0.2, 'base': 5, 'power': 10, 'pretty_name': 'Kellarn'})
Region.objects.update_or_create(name='centriss', defaults={'extremity': 0.3, 'base': 4, 'power': 10, 'pretty_name': 'Centriss'})
Region.objects.update_or_create(name='essianfoothills', defaults={'extremity': 0.2, 'base': 5, 'power': 10, 'pretty_name': 'Essian Foothills'})
Region.objects.update_or_create(name='shipyards', defaults={'extremity': 0.1, 'base': 5, 'power': 7, 'pretty_name': 'The Shipyards'})
Region.objects.update_or_create(name='firstcity', defaults={'extremity': 0.2, 'base': 3, 'power': 7, 'pretty_name': 'The First City'})
Region.objects.update_or_create(name='xilewood', defaults={'extremity': 0.5, 'base': 10, 'power': 10, 'pretty_name': 'The Xilewood'})
Region.objects.update_or_create(name='emmel', defaults={'extremity': 0.2, 'base': 5, 'power': 10, 'pretty_name': 'Emmel'})
Region.objects.update_or_create(name='tirelessnight', defaults={'extremity': 0.65, 'base': 3, 'power': 10, 'pretty_name': 'The Tireless Night'})
Region.objects.update_or_create(name='tentacular', defaults={'extremity': 0.7, 'base': 10, 'power': 10, 'pretty_name': 'The Tentacular'})
Region.objects.update_or_create(name='thewanderlands', defaults={'extremity': 0.2, 'base': 5, 'power': 10, 'pretty_name': 'The Wanderlands'})
Region.objects.update_or_create(name='ostentia', defaults={'extremity': 0.45, 'base': 5, 'power': 5, 'pretty_name': 'Ostentia'})
Region.objects.update_or_create(name='thehub', defaults={'extremity': 0.2, 'base': 5, 'power': 10, 'pretty_name': 'The Hub'})
Region.objects.update_or_create(name='theworldspine', defaults={'extremity': 0.2, 'base': 5, 'power': 10, 'pretty_name': 'The Worldspine'})
Region.objects.update_or_create(name='sinisteria', defaults={'extremity': 0.2, 'base': 5, 'power': 10, 'pretty_name': 'Sinisteria'})
Region.objects.update_or_create(name='riddlewood', defaults={'extremity': 0.2, 'base': 5, 'power': 10, 'pretty_name': 'The Riddlewoods'})
Region.objects.update_or_create(name='lostpeaks', defaults={'extremity': 0.2, 'base': 5, 'power': 10, 'pretty_name': 'The Lost Peaks'})
Region.objects.update_or_create(name='mormiria', defaults={'extremity': 0.2, 'base': 5, 'power': 10, 'pretty_name': 'Mormiria'})
Region.objects.update_or_create(name='reyawinn', defaults={'extremity': 0.2, 'base': 5, 'power': 10, 'pretty_name': 'Reyawinn'})

for r in Region.objects.all():
    r.save()


