Size.objects.create(name='puny',lookup_id=1,pretty_name='Puny')
Size.objects.create(name='tiny', lookup_id=2, pretty_name='Tiny')
Size.objects.create(name='small', lookup_id=3, pretty_name='Small')
Size.objects.create(name='medium', lookup_id=4, pretty_name='Medium')
Size.objects.create(name='large', lookup_id=5, pretty_name='Large')
Size.objects.create(name='very_large', lookup_id=6, pretty_name='Very Large')
Size.objects.create(name='jumbo', lookup_id=7, pretty_name='Jumbo')
Size.objects.create(name='humongus', lookup_id=8, pretty_name='Humongus')
Size.objects.create(name='massive', lookup_id=9, pretty_name='Massive')
Size.objects.create(name='gigantic', lookup_id=10, pretty_name='Gigantic')
Size.objects.create(name='collosal', lookup_id=11, pretty_name='Collosal')
Size.objects.create(name='cyclopean', lookup_id=12, pretty_name='Cyclopean')
Size.objects.create(name='primordial', lookup_id=13, pretty_name='Primordial')
Size.save()
