# Generated by Django 4.1.2 on 2023-02-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randoplant_game', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
