# Generated by Django 4.1.5 on 2023-02-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50)),
                ('continent_origin', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, default=None, max_length=300, null=True)),
                ('text', models.TextField(blank=True, default=None, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('base', models.IntegerField(default=0, null=True)),
                ('extremity', models.IntegerField(default=0, null=True)),
                ('power', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('pretty_name', models.TextField(max_length=25)),
                ('lookup_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50)),
                ('occurence_value', models.IntegerField(default=0, null=True)),
                ('common_value', models.IntegerField(default=0, null=True)),
                ('metal', models.FloatField(blank=True, default=0.0)),
                ('animal', models.FloatField(blank=True, default=0.0)),
                ('body_control', models.FloatField(blank=True, default=0.0)),
                ('comm_and_emp', models.FloatField(blank=True, default=0.0)),
                ('earth', models.FloatField(blank=True, default=0.0)),
                ('enchantment', models.FloatField(blank=True, default=0.0)),
                ('fire', models.FloatField(blank=True, default=0.0)),
                ('food', models.FloatField(blank=True, default=0.0)),
                ('healing', models.FloatField(blank=True, default=0.0)),
                ('illusion_and_creation', models.FloatField(blank=True, default=0.0)),
                ('knowledge', models.FloatField(blank=True, default=0.0)),
                ('light_and_dark', models.FloatField(blank=True, default=0.0)),
                ('make_and_break', models.FloatField(blank=True, default=0.0)),
                ('meta', models.FloatField(blank=True, default=0.0)),
                ('mind_control', models.FloatField(blank=True, default=0.0)),
                ('movement', models.FloatField(blank=True, default=0.0)),
                ('necromantic', models.FloatField(blank=True, default=0.0)),
                ('plant', models.FloatField(blank=True, default=0.0)),
                ('protection', models.FloatField(blank=True, default=0.0)),
                ('sounds', models.FloatField(blank=True, default=0.0)),
                ('water', models.FloatField(blank=True, default=0.0)),
                ('weather', models.FloatField(blank=True, default=0.0)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('culinary', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('poison', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('defense', models.TextField(blank=True, default=None, null=True)),
                ('chemical', models.CharField(blank=True, default=0.0, max_length=200, null=True)),
                ('symbolic', models.TextField(blank=True, default=0.0, max_length=200, null=True)),
                ('antidote', models.CharField(blank=True, default=0.0, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default=None, max_length=300, null=True)),
                ('continent_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='randoplant.region')),
            ],
        ),
    ]
