# Generated by Django 4.1.5 on 2023-01-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50)),
                ('occurence_value', models.IntegerField(default=0, null=True)),
                ('common_value', models.IntegerField(default=0, null=True)),
                ('metal', models.FloatField(blank=True, default=0.0)),
                ('animal', models.FloatField(blank=True, default=0.0)),
                ('body_control', models.FloatField(blank=True, default=0.0)),
                ('comm_and_emp', models.FloatField(blank=True, default=0.0)),
                ('earth', models.FloatField(blank=True, default=0.0)),
                ('enchantment', models.FloatField(blank=True, default=0.0)),
                ('fire', models.FloatField(blank=True, default=0.0)),
                ('food', models.FloatField(blank=True, default=0.0)),
                ('healing', models.FloatField(blank=True, default=0.0)),
                ('illusion_and_creation', models.FloatField(blank=True, default=0.0)),
                ('knowledge', models.FloatField(blank=True, default=0.0)),
                ('light_and_dark', models.FloatField(blank=True, default=0.0)),
                ('make_and_break', models.FloatField(blank=True, default=0.0)),
                ('meta', models.FloatField(blank=True, default=0.0)),
                ('mind_control', models.FloatField(blank=True, default=0.0)),
                ('movement', models.FloatField(blank=True, default=0.0)),
                ('necromantic', models.FloatField(blank=True, default=0.0)),
                ('plant', models.FloatField(blank=True, default=0.0)),
                ('protection', models.FloatField(blank=True, default=0.0)),
                ('sounds', models.FloatField(blank=True, default=0.0)),
                ('water', models.FloatField(blank=True, default=0.0)),
                ('weather', models.FloatField(blank=True, default=0.0)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('culinary', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('poison', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('defense', models.FloatField(blank=True, default=0.0, null=True)),
                ('chemical', models.FloatField(blank=True, default=0.0, null=True)),
                ('symbolic', models.FloatField(blank=True, default=0.0, null=True)),
                ('antidote', models.FloatField(blank=True, default=0.0, null=True)),
                ('continent_origin', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
