# Generated by Django 4.1.2 on 2023-01-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randoplant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='antidote',
            field=models.CharField(blank=True, default=0.0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='chemical',
            field=models.CharField(blank=True, default=0.0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='symbolic',
            field=models.TextField(blank=True, default=0.0, max_length=200, null=True),
        ),
    ]
