# Generated by Django 4.1.2 on 2023-02-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randoplant', '0002_alter_plant_antidote_alter_plant_chemical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='defense',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
