# Generated by Django 4.1.5 on 2023-02-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randoplant', '0003_region_pretty_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('adjective', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
