# Generated by Django 4.1.5 on 2023-06-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randoplant', '0005_alter_region_extremity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='flavor',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
